### ISSUE TITLE
Question about MVTools, mvmulti and Oyster

### ISSUE THREAD

**Issue by chaseemory** [IFeelBloated/Oyster#4]
I am trying to get Oyster working, but I was having a lot of trouble with mvmulti. mvmulti.py used to be in the mvtools_sf repo, but it isn't anymore. It's only in the legacy branch. But Osyter still relies on it. I went and grabbed it from that branch. and now I get this error. I have the newest version of Oyster and MVTools_sf.

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1956, in vapoursynth.vpy_evaluateScript
  File "src/cython/vapoursynth.pyx", line 1957, in vapoursynth.vpy_evaluateScript
  File "lucky_strike.vpy", line 12, in <module>
    sb = Oyster.Basic(y, Oyster.Super(y))
  File "/usr/lib/python3.8/site-packages/Oyster.py", line 270, in Basic
    clip                       = internal.basic(core, src, super, radius, pel, sad, short_time, color)
  File "/usr/lib/python3.8/site-packages/Oyster.py", line 133, in basic
    clip                 = core.MDegrainN(src, supersharp, vmulti, tr=radius, thsad=sad, plane=plane, **mdegrain_args)
  File "/usr/lib/python3.8/site-packages/mvmulti.py", line 80, in DegrainN
    dgn       = core.mvsf.Degrain6(clip, super, bvn(1), fvn(1), bvn(2), fvn(2), bvn(3), fvn(3), bvn(4), fvn(4), bvn(5), fvn(5), bvn(6), fvn(6), thsad=thsad, plane=plane, limit=limit, thscd1=thscd1, thscd2=thscd2)
  File "src/cython/vapoursynth.pyx", line 1727, in vapoursynth.Plugin.__getattr__
AttributeError: There is no function named Degrain6

**Comment by IFeelBloated** [comment]
the mvmulti module is no longer required.

**Comment by chaseemory** [comment]
oh, thank you!
