### ISSUE TITLE
is mvsf.Degrain recently deprecated?

### ISSUE THREAD

**Issue by ErieSinger** [IFeelBloated/Oyster#5]
I'm trying to get Oyster up and running in Vapoursynth R51, and am getting:

File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
File "F:/Vidtemp/scripts/Intro1080.vpy", line 24, in 
supervideo = oys.Super(video, pel=4)
File "src\cython\vapoursynth.pyx", line 1934, in vapoursynth.Plugin.__getattr__
**AttributeError: There is no function named Degrain**

looking through the current mvsf functions, I don't see Degrain, only Degrain[1...24], so I tried running the degrain line myself, using info cribbed from line 132 from Oyster.py, using each of these, and end up getting an argument error:

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
File "F:/Vidtemp/scripts/MaxxIntro1080.vpy", line 24, in 
video = core.mvsf.Degrain4(video, supersharp, vmulti, thsad=sad, plane=plane)
NameError: name 'supersharp' is not defined

**Comment by IFeelBloated** [comment]
you are using an older version of MVTools-sf, the latest version of mvtools-sf only has one Degrain function and Degrain1-24 were all removed.

**Comment by IFeelBloated** [comment]
you can find the latest builds here: https://forum.doom9.org/showthread.php?p=1912769#post1912769
